#!/bin/bash
MAUDE=/Users/cbraga/Documents/bin/Maude-3//maude-Yices2.darwin64*
IMP_DIR=./
if [ "$TERM_PROGRAM" = "iTerm.app" ] ;
then
  ./imgcat ./img/imp.jpg
fi
if [ "$1" = "" ] ;
then
  $MAUDE -no-banner $IMP_DIR/maude/imp.maude
  exit 0
fi
while [ "$1" != "" ]; do
  $MAUDE -no-banner $IMP_DIR/maude/imp.maude "$1"
  shift
done
